### ISSUE TITLE
Mixin Guards

### ISSUE THREAD

**Issue by brunowego** [duvillierA/grunt-less-to-sass#3]
You know if is possible convert Mixin Guards to Sass syntax?

Take a look http://lesscss.org/features/#mixin-guards-feature

**Comment by brunowego** [comment]
Examples of how it would be with SASS https://gist.github.com/chriseppstein/674726#conditionals--control-structures

**Comment by brunowego** [comment]
Fixed with:

``` coffee
{
  pattern: /\.([\w-_]*)\s*\((.*)\)\s*when\s*\((.*)[=\s*?](.*)\)\s*\{(\s*)([^}]+)}[;]?/gi
  replacement: '@if $3$4 {$5@mixin $1($2){$5$6}}'
  order: 2
}
```

**Comment by brunowego** [comment]
But if I use more advanced code, like:

``` less
.window-shadow(@shadow-color) when not (@shadow-color = transparent) {
    border-color: @shadow-color;
    .box-shadow(@window-shadow-style lighten(@shadow-color, 50%));

    &.k-state-focused {
        border-color: @shadow-color;
        .box-shadow(@window-shadow-style @shadow-color);
    }
}

.window-shadow(@shadow-color) when (@shadow-color = transparent) and (lightness(@widget-background-color) < 50%) {
    border-color: @widget-border-color;

    &.k-state-focused {
        border-color: lighten(@widget-border-color, 20%);
    }
}

.guarded-border-radius(@value) when (@value < 0) {
    border-radius: 0;
}
```

I will get issues with final code. Can help with this?
