### ISSUE TITLE
Infinite arguments

### ISSUE THREAD

**Issue by brunowego** [duvillierA/grunt-less-to-sass#4]
If you get a code like this:

``` less
.transition(...) {
    -webkit-transition: @arguments;
    -moz-transition: @arguments;
    -ms-transition: @arguments;
    -o-transition: @arguments;
    transition: @arguments;
}
```

You will get a issue in final code. At this moment I fix with follow code:

``` coffee
{
  pattern: /\.([\w\-]*)\s*\((.*)\)\s*\{/gi
  replacement: (match, name, argument) ->
    if argument == '...'
      argument = '$arguments...'

    '@mixin ' + name + '(' + argument + '){'
  order: 3
}
```

But I not right if this is the best match.
